<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anirudhs-MacBook-Pro.local" failures="0" tests="1" name="org.testing.TestScripts.TC2" time="16.615" errors="1" timestamp="2021-12-19T01:31:58 IST" skipped="0">
  <testcase classname="org.testing.TestScripts.TC2" name="TC_02" time="16.615">
    <error message="Cannot create directory &#039;/YTFramework/Screenshot&#039;." type="java.io.IOException">
      <![CDATA[java.io.IOException: Cannot create directory '/YTFramework/Screenshot'.
at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200)
at org.apache.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:843)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
at org.testing.utilities.ScreenShotCapture.TakeScreeShot(ScreenShotCapture.java:15)
at org.testing.TestScripts.TC2.TC_02(TC2.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testing.Trigger.Runner.main(Runner.java:73)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </error>
  </testcase> <!-- TC_02 -->
  <system-out/>
</testsuite> <!-- org.testing.TestScripts.TC2 -->
